# Generated by Django 3.1 on 2020-08-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapi', '0002_auto_20200819_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Car',
            new_name='car',
        ),
    ]
